version: '3.9'
services:
  app:
    restart: always
    build: .
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    volumes:
      - .:/app                        
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    restart: always
    image: postgres:16.3
    env_file:
      - .env    
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase

# volumes:
#   postgres_data: {}
